Update Submit verification Caught Profile page up with rest of pages + Address autocomplete
PSU-CapstoneBrownHope/BrownHopeAidApp pull request #282
Opened 2022-06-25 00:23 UTC by baloveless

- Changed submit verify to be easier to understand
- Modified formUtil to accommodate profile page use
    - Added param for passing in a swap state function (i.e. switch from seeing to editting user information)
    - Param for passing in address autocomplete function (optional functions could be changed to being passed in by JSON)
- Implemented simple address autocomplete. Possibly overly simple because of the use of datalist html item that excludes anything that isn't a close match. Usually only shows one option. 
- removed some of the button options I added as they were redundant.

2022-06-25 00:49 UTC, mackfoggia requested changes

2022-06-25 00:49 UTC, mackfoggia commented on frontend/src/util/config.ts
> +//const server = 'http://appstatus.brownhope.org';
```suggestion
const server = 'http://appstatus.brownhope.org';
```

2022-06-26 00:29 UTC, baloveless commented
Made the autocomplete better, now it shows more options and is easier to understand than before. Also updated all the comments to make the whole thing easier to understand.

2022-06-26 00:36 UTC, mackfoggia approved these changes

2022-06-26 00:39 UTC, merged